"use client";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deletePortfolioMedia, uploadPortfolioMedia } from "@/app/actions/cms";
export type MediaObject = { name: string; id?: string; updated_at?: string; publicUrl?: string; metadata?: { mimetype?: string; size?: number } | null };
export function MediaManager({ files }: { files: MediaObject[] }) {
  const input = useRef<HTMLInputElement>(null); const [pending, startTransition] = useTransition(); const [notice, setNotice] = useState(""); const router = useRouter();
  function upload(file?: File) { if (!file) return; const form = new FormData(); form.set("file", file); startTransition(async () => { const result = await uploadPortfolioMedia(form); if (!result) return; setNotice(result.ok ? "Uploaded." : result.message); if (result.ok) router.refresh(); }); }
  function remove(path: string) { if (!confirm(`Delete ${path}?`)) return; const form = new FormData(); form.set("path", path); startTransition(async () => { const result = await deletePortfolioMedia(form); if (!result) return; setNotice(result.message); if (result.ok) router.refresh(); }); }
  return <section><header className="mb-8 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow mb-2">Portfolio assets</p><h1 className="text-3xl font-semibold">Media</h1><p className="mt-2 text-sm text-muted">Uploaded media is available for project galleries and cover images.</p></div><><input ref={input} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,application/pdf" className="hidden" onChange={event => upload(event.target.files?.[0])} /><button disabled={pending} onClick={() => input.current?.click()} className="rounded-lg bg-fg px-4 py-2 text-sm text-ink">{pending ? "Working…" : "Upload media"}</button></></header>{notice && <p role="status" className="mb-4 text-sm text-muted">{notice}</p>}<ul className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{files.map(file => <li key={file.name} className="glass overflow-hidden"><div className="flex aspect-video items-center justify-center bg-surface">{file.metadata?.mimetype?.startsWith("image/") && file.publicUrl ? <img src={file.publicUrl} alt={file.name} className="h-full w-full object-cover" /> : <span className="text-sm text-muted">{file.metadata?.mimetype || "File"}</span>}</div><div className="p-4"><p className="truncate text-sm">{file.name}</p><button disabled={pending} onClick={() => remove(file.name)} className="mt-3 text-xs text-red-400">Delete</button></div></li>)}{files.length === 0 && <li className="glass col-span-full p-8 text-sm text-muted">No uploaded media yet.</li>}</ul></section>;
}
