"use client";

import { useActionState, useState } from "react";
import { saveSettings } from "@/app/actions/cms";
import type { PortfolioSettings } from "@/lib/portfolio-types";

const field = "mt-1 w-full rounded-lg border border-line bg-ink px-3 py-2 text-sm";
export function SettingsForm({ initial }: { initial: PortfolioSettings }) {
  const [settings, setSettings] = useState(initial);
  const [state, action, pending] = useActionState(saveSettings, null);
  const groups = ["profile", "hero", "about", "seo"] as const;
  return <form action={action} className="space-y-6">
    <input type="hidden" name="settings" value={JSON.stringify(settings)} />
    <header><p className="eyebrow mb-2">Site configuration</p><h1 className="text-3xl font-semibold">Homepage & settings</h1><p className="mt-2 text-sm text-muted">Saving publishes these settings to your portfolio.</p></header>
    {groups.map(group => <details key={group} className="glass p-5" open={group === "profile"}><summary className="cursor-pointer font-medium capitalize">{group}</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{Object.entries(settings[group]).filter(([, value]) => typeof value === "string").map(([key, value]) => <label key={key} className="text-sm capitalize text-muted">{key.replace(/([A-Z])/g, " $1")}<textarea rows={key === "body" || key === "description" || key === "bio" ? 4 : 1} className={field} value={String(value)} onChange={event => setSettings({ ...settings, [group]: { ...settings[group], [key]: event.target.value } })} /></label>)}</div></details>)}
    <section className="glass p-5"><h2 className="mb-4 font-medium">Section visibility & order</h2><div className="space-y-3">{settings.sections.map((section, index) => <div key={section.id} className="grid items-center gap-3 border-b border-line pb-3 sm:grid-cols-[1fr_2fr_6rem]"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={section.visible} onChange={event => setSettings({ ...settings, sections: settings.sections.map((item, i) => i === index ? { ...item, visible: event.target.checked } : item) })} />{section.label}</label><label className="text-xs text-muted">Heading<input className={field} value={section.heading} onChange={event => setSettings({ ...settings, sections: settings.sections.map((item, i) => i === index ? { ...item, heading: event.target.value } : item) })} /></label><label className="text-xs text-muted">Order<input className={field} type="number" value={section.order} onChange={event => setSettings({ ...settings, sections: settings.sections.map((item, i) => i === index ? { ...item, order: Number(event.target.value) } : item) })} /></label></div>)}</div></section>
    <section className="glass p-5"><h2 className="mb-3 font-medium">About facts</h2>{settings.about.facts.map((fact, index) => <div key={index} className="mb-3 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><label className="text-xs text-muted">Label<input className={field} value={fact.label} onChange={event => setSettings({ ...settings, about: { ...settings.about, facts: settings.about.facts.map((item, i) => i === index ? { ...item, label: event.target.value } : item) } })} /></label><label className="text-xs text-muted">Value<input className={field} value={fact.value} onChange={event => setSettings({ ...settings, about: { ...settings.about, facts: settings.about.facts.map((item, i) => i === index ? { ...item, value: event.target.value } : item) } })} /></label><button type="button" className="text-xs text-muted" onClick={() => setSettings({ ...settings, about: { ...settings.about, facts: settings.about.facts.filter((_, i) => i !== index) } })}>Remove fact</button></div>)}<button type="button" className="text-sm text-cyan" onClick={() => setSettings({ ...settings, about: { ...settings.about, facts: [...settings.about.facts, { label: "", value: "" }] } })}>+ Add fact</button></section>
    <section className="glass space-y-4 p-5"><h2 className="font-medium">Appearance</h2><label className="block text-sm text-muted">Theme<select className={field} value={settings.appearance.theme} onChange={event => setSettings({ ...settings, appearance: { ...settings.appearance, theme: event.target.value as PortfolioSettings["appearance"]["theme"] } })}><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></label><label className="block text-sm text-muted">Accent<input className={field} value={settings.appearance.accent} onChange={event => setSettings({ ...settings, appearance: { ...settings.appearance, accent: event.target.value } })} /></label>{(["motion", "show3d"] as const).map(key => <label key={key} className="mr-6 inline-flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.appearance[key]} onChange={event => setSettings({ ...settings, appearance: { ...settings.appearance, [key]: event.target.checked } })} />{key === "motion" ? "Enable motion" : "Enable 3D"}</label>)}</section>
    <section className="glass space-y-4 p-5"><h2 className="font-medium">Personal details</h2><label className="block text-sm text-muted">Philosophy<textarea className={field} rows={3} value={settings.philosophy} onChange={event => setSettings({ ...settings, philosophy: event.target.value })} /></label><label className="block text-sm text-muted">Current status (one per line)<textarea className={field} value={settings.currentStatus.join("\n")} onChange={event => setSettings({ ...settings, currentStatus: event.target.value.split("\n") })} /></label><label className="block text-sm text-muted">Social links (one per line: label | URL)<textarea className={field} value={settings.socials.map(social => `${social.label} | ${social.url}`).join("\n")} onChange={event => setSettings({ ...settings, socials: event.target.value.split("\n").map(line => { const [label, ...url] = line.split("|"); return { label: label.trim(), url: url.join("|").trim() }; }) })} /></label></section>
    <div className="sticky bottom-4 rounded-xl border border-line bg-ink-2 p-4 shadow-xl"><button disabled={pending} className="rounded-lg bg-fg px-5 py-2 text-sm font-medium text-ink disabled:opacity-50">{pending ? "Saving…" : "Publish settings"}</button>{state && <p role="status" className={`mt-2 text-sm ${state.ok ? "text-cyan" : "text-red-400"}`}>{state.message}</p>}</div>
  </form>;
}
